// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Listener is the predicate function for listener builders.
type Listener func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)
