// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nu11zy/rscc/internal/database/ent/agent"
	"github.com/nu11zy/rscc/internal/database/ent/predicate"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetComment sets the "comment" field.
func (_u *AgentUpdate) SetComment(v string) *AgentUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableComment(v *string) *AgentUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *AgentUpdate) ClearComment() *AgentUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetURL sets the "url" field.
func (_u *AgentUpdate) SetURL(v string) *AgentUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableURL(v *string) *AgentUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *AgentUpdate) ClearURL() *AgentUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetHosted sets the "hosted" field.
func (_u *AgentUpdate) SetHosted(v bool) *AgentUpdate {
	_u.mutation.SetHosted(v)
	return _u
}

// SetNillableHosted sets the "hosted" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableHosted(v *bool) *AgentUpdate {
	if v != nil {
		_u.SetHosted(*v)
	}
	return _u
}

// SetCallbacks sets the "callbacks" field.
func (_u *AgentUpdate) SetCallbacks(v int) *AgentUpdate {
	_u.mutation.ResetCallbacks()
	_u.mutation.SetCallbacks(v)
	return _u
}

// SetNillableCallbacks sets the "callbacks" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableCallbacks(v *int) *AgentUpdate {
	if v != nil {
		_u.SetCallbacks(*v)
	}
	return _u
}

// AddCallbacks adds value to the "callbacks" field.
func (_u *AgentUpdate) AddCallbacks(v int) *AgentUpdate {
	_u.mutation.AddCallbacks(v)
	return _u
}

// SetDownloads sets the "downloads" field.
func (_u *AgentUpdate) SetDownloads(v int) *AgentUpdate {
	_u.mutation.ResetDownloads()
	_u.mutation.SetDownloads(v)
	return _u
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableDownloads(v *int) *AgentUpdate {
	if v != nil {
		_u.SetDownloads(*v)
	}
	return _u
}

// AddDownloads adds value to the "downloads" field.
func (_u *AgentUpdate) AddDownloads(v int) *AgentUpdate {
	_u.mutation.AddDownloads(v)
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(agent.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(agent.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(agent.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(agent.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Hosted(); ok {
		_spec.SetField(agent.FieldHosted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Callbacks(); ok {
		_spec.SetField(agent.FieldCallbacks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCallbacks(); ok {
		_spec.AddField(agent.FieldCallbacks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Downloads(); ok {
		_spec.SetField(agent.FieldDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloads(); ok {
		_spec.AddField(agent.FieldDownloads, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetComment sets the "comment" field.
func (_u *AgentUpdateOne) SetComment(v string) *AgentUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableComment(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *AgentUpdateOne) ClearComment() *AgentUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetURL sets the "url" field.
func (_u *AgentUpdateOne) SetURL(v string) *AgentUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableURL(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *AgentUpdateOne) ClearURL() *AgentUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetHosted sets the "hosted" field.
func (_u *AgentUpdateOne) SetHosted(v bool) *AgentUpdateOne {
	_u.mutation.SetHosted(v)
	return _u
}

// SetNillableHosted sets the "hosted" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableHosted(v *bool) *AgentUpdateOne {
	if v != nil {
		_u.SetHosted(*v)
	}
	return _u
}

// SetCallbacks sets the "callbacks" field.
func (_u *AgentUpdateOne) SetCallbacks(v int) *AgentUpdateOne {
	_u.mutation.ResetCallbacks()
	_u.mutation.SetCallbacks(v)
	return _u
}

// SetNillableCallbacks sets the "callbacks" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableCallbacks(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetCallbacks(*v)
	}
	return _u
}

// AddCallbacks adds value to the "callbacks" field.
func (_u *AgentUpdateOne) AddCallbacks(v int) *AgentUpdateOne {
	_u.mutation.AddCallbacks(v)
	return _u
}

// SetDownloads sets the "downloads" field.
func (_u *AgentUpdateOne) SetDownloads(v int) *AgentUpdateOne {
	_u.mutation.ResetDownloads()
	_u.mutation.SetDownloads(v)
	return _u
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableDownloads(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetDownloads(*v)
	}
	return _u
}

// AddDownloads adds value to the "downloads" field.
func (_u *AgentUpdateOne) AddDownloads(v int) *AgentUpdateOne {
	_u.mutation.AddDownloads(v)
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(agent.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(agent.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(agent.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(agent.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Hosted(); ok {
		_spec.SetField(agent.FieldHosted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Callbacks(); ok {
		_spec.SetField(agent.FieldCallbacks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCallbacks(); ok {
		_spec.AddField(agent.FieldCallbacks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Downloads(); ok {
		_spec.SetField(agent.FieldDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloads(); ok {
		_spec.AddField(agent.FieldDownloads, field.TypeInt, value)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
