// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nu11zy/rscc/internal/database/ent/agent"
)

// AgentCreate is the builder for creating a Agent entity.
type AgentCreate struct {
	config
	mutation *AgentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCreate) SetCreatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableCreatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AgentCreate) SetName(v string) *AgentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *AgentCreate) SetComment(v string) *AgentCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *AgentCreate) SetNillableComment(v *string) *AgentCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetOs sets the "os" field.
func (_c *AgentCreate) SetOs(v string) *AgentCreate {
	_c.mutation.SetOs(v)
	return _c
}

// SetArch sets the "arch" field.
func (_c *AgentCreate) SetArch(v string) *AgentCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetServers sets the "servers" field.
func (_c *AgentCreate) SetServers(v []string) *AgentCreate {
	_c.mutation.SetServers(v)
	return _c
}

// SetShared sets the "shared" field.
func (_c *AgentCreate) SetShared(v bool) *AgentCreate {
	_c.mutation.SetShared(v)
	return _c
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_c *AgentCreate) SetNillableShared(v *bool) *AgentCreate {
	if v != nil {
		_c.SetShared(*v)
	}
	return _c
}

// SetPie sets the "pie" field.
func (_c *AgentCreate) SetPie(v bool) *AgentCreate {
	_c.mutation.SetPie(v)
	return _c
}

// SetNillablePie sets the "pie" field if the given value is not nil.
func (_c *AgentCreate) SetNillablePie(v *bool) *AgentCreate {
	if v != nil {
		_c.SetPie(*v)
	}
	return _c
}

// SetGarble sets the "garble" field.
func (_c *AgentCreate) SetGarble(v bool) *AgentCreate {
	_c.mutation.SetGarble(v)
	return _c
}

// SetNillableGarble sets the "garble" field if the given value is not nil.
func (_c *AgentCreate) SetNillableGarble(v *bool) *AgentCreate {
	if v != nil {
		_c.SetGarble(*v)
	}
	return _c
}

// SetSubsystems sets the "subsystems" field.
func (_c *AgentCreate) SetSubsystems(v []string) *AgentCreate {
	_c.mutation.SetSubsystems(v)
	return _c
}

// SetXxhash sets the "xxhash" field.
func (_c *AgentCreate) SetXxhash(v string) *AgentCreate {
	_c.mutation.SetXxhash(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *AgentCreate) SetPath(v string) *AgentCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *AgentCreate) SetURL(v string) *AgentCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *AgentCreate) SetNillableURL(v *string) *AgentCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetHosted sets the "hosted" field.
func (_c *AgentCreate) SetHosted(v bool) *AgentCreate {
	_c.mutation.SetHosted(v)
	return _c
}

// SetNillableHosted sets the "hosted" field if the given value is not nil.
func (_c *AgentCreate) SetNillableHosted(v *bool) *AgentCreate {
	if v != nil {
		_c.SetHosted(*v)
	}
	return _c
}

// SetCallbacks sets the "callbacks" field.
func (_c *AgentCreate) SetCallbacks(v int) *AgentCreate {
	_c.mutation.SetCallbacks(v)
	return _c
}

// SetNillableCallbacks sets the "callbacks" field if the given value is not nil.
func (_c *AgentCreate) SetNillableCallbacks(v *int) *AgentCreate {
	if v != nil {
		_c.SetCallbacks(*v)
	}
	return _c
}

// SetDownloads sets the "downloads" field.
func (_c *AgentCreate) SetDownloads(v int) *AgentCreate {
	_c.mutation.SetDownloads(v)
	return _c
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_c *AgentCreate) SetNillableDownloads(v *int) *AgentCreate {
	if v != nil {
		_c.SetDownloads(*v)
	}
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *AgentCreate) SetPublicKey(v []byte) *AgentCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AgentCreate) SetID(v string) *AgentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableID(v *string) *AgentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AgentMutation object of the builder.
func (_c *AgentCreate) Mutation() *AgentMutation {
	return _c.mutation
}

// Save creates the Agent in the database.
func (_c *AgentCreate) Save(ctx context.Context) (*Agent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCreate) SaveX(ctx context.Context) *Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Shared(); !ok {
		v := agent.DefaultShared
		_c.mutation.SetShared(v)
	}
	if _, ok := _c.mutation.Pie(); !ok {
		v := agent.DefaultPie
		_c.mutation.SetPie(v)
	}
	if _, ok := _c.mutation.Garble(); !ok {
		v := agent.DefaultGarble
		_c.mutation.SetGarble(v)
	}
	if _, ok := _c.mutation.Subsystems(); !ok {
		v := agent.DefaultSubsystems
		_c.mutation.SetSubsystems(v)
	}
	if _, ok := _c.mutation.Hosted(); !ok {
		v := agent.DefaultHosted
		_c.mutation.SetHosted(v)
	}
	if _, ok := _c.mutation.Callbacks(); !ok {
		v := agent.DefaultCallbacks
		_c.mutation.SetCallbacks(v)
	}
	if _, ok := _c.mutation.Downloads(); !ok {
		v := agent.DefaultDownloads
		_c.mutation.SetDownloads(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Agent.created_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Agent.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Os(); !ok {
		return &ValidationError{Name: "os", err: errors.New(`ent: missing required field "Agent.os"`)}
	}
	if v, ok := _c.mutation.Os(); ok {
		if err := agent.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Agent.os": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "Agent.arch"`)}
	}
	if v, ok := _c.mutation.Arch(); ok {
		if err := agent.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "Agent.arch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Servers(); !ok {
		return &ValidationError{Name: "servers", err: errors.New(`ent: missing required field "Agent.servers"`)}
	}
	if _, ok := _c.mutation.Shared(); !ok {
		return &ValidationError{Name: "shared", err: errors.New(`ent: missing required field "Agent.shared"`)}
	}
	if _, ok := _c.mutation.Pie(); !ok {
		return &ValidationError{Name: "pie", err: errors.New(`ent: missing required field "Agent.pie"`)}
	}
	if _, ok := _c.mutation.Garble(); !ok {
		return &ValidationError{Name: "garble", err: errors.New(`ent: missing required field "Agent.garble"`)}
	}
	if _, ok := _c.mutation.Subsystems(); !ok {
		return &ValidationError{Name: "subsystems", err: errors.New(`ent: missing required field "Agent.subsystems"`)}
	}
	if _, ok := _c.mutation.Xxhash(); !ok {
		return &ValidationError{Name: "xxhash", err: errors.New(`ent: missing required field "Agent.xxhash"`)}
	}
	if v, ok := _c.mutation.Xxhash(); ok {
		if err := agent.XxhashValidator(v); err != nil {
			return &ValidationError{Name: "xxhash", err: fmt.Errorf(`ent: validator failed for field "Agent.xxhash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Agent.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := agent.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Agent.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hosted(); !ok {
		return &ValidationError{Name: "hosted", err: errors.New(`ent: missing required field "Agent.hosted"`)}
	}
	if _, ok := _c.mutation.Callbacks(); !ok {
		return &ValidationError{Name: "callbacks", err: errors.New(`ent: missing required field "Agent.callbacks"`)}
	}
	if _, ok := _c.mutation.Downloads(); !ok {
		return &ValidationError{Name: "downloads", err: errors.New(`ent: missing required field "Agent.downloads"`)}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "Agent.public_key"`)}
	}
	if v, ok := _c.mutation.PublicKey(); ok {
		if err := agent.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "Agent.public_key": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentCreate) sqlSave(ctx context.Context) (*Agent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Agent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCreate) createSpec() (*Agent, *sqlgraph.CreateSpec) {
	var (
		_node = &Agent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agent.Table, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(agent.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Os(); ok {
		_spec.SetField(agent.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(agent.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.Servers(); ok {
		_spec.SetField(agent.FieldServers, field.TypeJSON, value)
		_node.Servers = value
	}
	if value, ok := _c.mutation.Shared(); ok {
		_spec.SetField(agent.FieldShared, field.TypeBool, value)
		_node.Shared = value
	}
	if value, ok := _c.mutation.Pie(); ok {
		_spec.SetField(agent.FieldPie, field.TypeBool, value)
		_node.Pie = value
	}
	if value, ok := _c.mutation.Garble(); ok {
		_spec.SetField(agent.FieldGarble, field.TypeBool, value)
		_node.Garble = value
	}
	if value, ok := _c.mutation.Subsystems(); ok {
		_spec.SetField(agent.FieldSubsystems, field.TypeJSON, value)
		_node.Subsystems = value
	}
	if value, ok := _c.mutation.Xxhash(); ok {
		_spec.SetField(agent.FieldXxhash, field.TypeString, value)
		_node.Xxhash = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(agent.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(agent.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Hosted(); ok {
		_spec.SetField(agent.FieldHosted, field.TypeBool, value)
		_node.Hosted = value
	}
	if value, ok := _c.mutation.Callbacks(); ok {
		_spec.SetField(agent.FieldCallbacks, field.TypeInt, value)
		_node.Callbacks = value
	}
	if value, ok := _c.mutation.Downloads(); ok {
		_spec.SetField(agent.FieldDownloads, field.TypeInt, value)
		_node.Downloads = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(agent.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	return _node, _spec
}

// AgentCreateBulk is the builder for creating many Agent entities in bulk.
type AgentCreateBulk struct {
	config
	err      error
	builders []*AgentCreate
}

// Save creates the Agent entities in the database.
func (_c *AgentCreateBulk) Save(ctx context.Context) ([]*Agent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Agent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCreateBulk) SaveX(ctx context.Context) []*Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
