// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rscc/internal/database/ent/listener"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ListenerCreate is the builder for creating a Listener entity.
type ListenerCreate struct {
	config
	mutation *ListenerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (lc *ListenerCreate) SetName(s string) *ListenerCreate {
	lc.mutation.SetName(s)
	return lc
}

// SetPrivateKey sets the "private_key" field.
func (lc *ListenerCreate) SetPrivateKey(b []byte) *ListenerCreate {
	lc.mutation.SetPrivateKey(b)
	return lc
}

// SetID sets the "id" field.
func (lc *ListenerCreate) SetID(s string) *ListenerCreate {
	lc.mutation.SetID(s)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *ListenerCreate) SetNillableID(s *string) *ListenerCreate {
	if s != nil {
		lc.SetID(*s)
	}
	return lc
}

// Mutation returns the ListenerMutation object of the builder.
func (lc *ListenerCreate) Mutation() *ListenerMutation {
	return lc.mutation
}

// Save creates the Listener in the database.
func (lc *ListenerCreate) Save(ctx context.Context) (*Listener, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *ListenerCreate) SaveX(ctx context.Context) *Listener {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *ListenerCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *ListenerCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *ListenerCreate) defaults() {
	if _, ok := lc.mutation.ID(); !ok {
		v := listener.DefaultID()
		lc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *ListenerCreate) check() error {
	if _, ok := lc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Listener.name"`)}
	}
	if v, ok := lc.mutation.Name(); ok {
		if err := listener.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Listener.name": %w`, err)}
		}
	}
	if _, ok := lc.mutation.PrivateKey(); !ok {
		return &ValidationError{Name: "private_key", err: errors.New(`ent: missing required field "Listener.private_key"`)}
	}
	if v, ok := lc.mutation.PrivateKey(); ok {
		if err := listener.PrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "private_key", err: fmt.Errorf(`ent: validator failed for field "Listener.private_key": %w`, err)}
		}
	}
	return nil
}

func (lc *ListenerCreate) sqlSave(ctx context.Context) (*Listener, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Listener.ID type: %T", _spec.ID.Value)
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *ListenerCreate) createSpec() (*Listener, *sqlgraph.CreateSpec) {
	var (
		_node = &Listener{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(listener.Table, sqlgraph.NewFieldSpec(listener.FieldID, field.TypeString))
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := lc.mutation.Name(); ok {
		_spec.SetField(listener.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := lc.mutation.PrivateKey(); ok {
		_spec.SetField(listener.FieldPrivateKey, field.TypeBytes, value)
		_node.PrivateKey = value
	}
	return _node, _spec
}

// ListenerCreateBulk is the builder for creating many Listener entities in bulk.
type ListenerCreateBulk struct {
	config
	err      error
	builders []*ListenerCreate
}

// Save creates the Listener entities in the database.
func (lcb *ListenerCreateBulk) Save(ctx context.Context) ([]*Listener, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Listener, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListenerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *ListenerCreateBulk) SaveX(ctx context.Context) []*Listener {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *ListenerCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *ListenerCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
