// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rscc/internal/database/ent/listener"
	"rscc/internal/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ListenerDelete is the builder for deleting a Listener entity.
type ListenerDelete struct {
	config
	hooks    []Hook
	mutation *ListenerMutation
}

// Where appends a list predicates to the ListenerDelete builder.
func (ld *ListenerDelete) Where(ps ...predicate.Listener) *ListenerDelete {
	ld.mutation.Where(ps...)
	return ld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ld *ListenerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ld.sqlExec, ld.mutation, ld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ld *ListenerDelete) ExecX(ctx context.Context) int {
	n, err := ld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ld *ListenerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(listener.Table, sqlgraph.NewFieldSpec(listener.FieldID, field.TypeString))
	if ps := ld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ld.mutation.done = true
	return affected, err
}

// ListenerDeleteOne is the builder for deleting a single Listener entity.
type ListenerDeleteOne struct {
	ld *ListenerDelete
}

// Where appends a list predicates to the ListenerDelete builder.
func (ldo *ListenerDeleteOne) Where(ps ...predicate.Listener) *ListenerDeleteOne {
	ldo.ld.mutation.Where(ps...)
	return ldo
}

// Exec executes the deletion query.
func (ldo *ListenerDeleteOne) Exec(ctx context.Context) error {
	n, err := ldo.ld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{listener.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ldo *ListenerDeleteOne) ExecX(ctx context.Context) {
	if err := ldo.Exec(ctx); err != nil {
		panic(err)
	}
}
