// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rscc/internal/database/ent/operator"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OperatorCreate is the builder for creating a Operator entity.
type OperatorCreate struct {
	config
	mutation *OperatorMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (oc *OperatorCreate) SetName(s string) *OperatorCreate {
	oc.mutation.SetName(s)
	return oc
}

// SetLastLogin sets the "last_login" field.
func (oc *OperatorCreate) SetLastLogin(t time.Time) *OperatorCreate {
	oc.mutation.SetLastLogin(t)
	return oc
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (oc *OperatorCreate) SetNillableLastLogin(t *time.Time) *OperatorCreate {
	if t != nil {
		oc.SetLastLogin(*t)
	}
	return oc
}

// SetPublicKey sets the "public_key" field.
func (oc *OperatorCreate) SetPublicKey(s string) *OperatorCreate {
	oc.mutation.SetPublicKey(s)
	return oc
}

// SetIsAdmin sets the "is_admin" field.
func (oc *OperatorCreate) SetIsAdmin(b bool) *OperatorCreate {
	oc.mutation.SetIsAdmin(b)
	return oc
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (oc *OperatorCreate) SetNillableIsAdmin(b *bool) *OperatorCreate {
	if b != nil {
		oc.SetIsAdmin(*b)
	}
	return oc
}

// SetID sets the "id" field.
func (oc *OperatorCreate) SetID(s string) *OperatorCreate {
	oc.mutation.SetID(s)
	return oc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (oc *OperatorCreate) SetNillableID(s *string) *OperatorCreate {
	if s != nil {
		oc.SetID(*s)
	}
	return oc
}

// Mutation returns the OperatorMutation object of the builder.
func (oc *OperatorCreate) Mutation() *OperatorMutation {
	return oc.mutation
}

// Save creates the Operator in the database.
func (oc *OperatorCreate) Save(ctx context.Context) (*Operator, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OperatorCreate) SaveX(ctx context.Context) *Operator {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OperatorCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OperatorCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OperatorCreate) defaults() {
	if _, ok := oc.mutation.IsAdmin(); !ok {
		v := operator.DefaultIsAdmin
		oc.mutation.SetIsAdmin(v)
	}
	if _, ok := oc.mutation.ID(); !ok {
		v := operator.DefaultID()
		oc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OperatorCreate) check() error {
	if _, ok := oc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Operator.name"`)}
	}
	if v, ok := oc.mutation.Name(); ok {
		if err := operator.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Operator.name": %w`, err)}
		}
	}
	if _, ok := oc.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "Operator.public_key"`)}
	}
	if v, ok := oc.mutation.PublicKey(); ok {
		if err := operator.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "Operator.public_key": %w`, err)}
		}
	}
	if _, ok := oc.mutation.IsAdmin(); !ok {
		return &ValidationError{Name: "is_admin", err: errors.New(`ent: missing required field "Operator.is_admin"`)}
	}
	return nil
}

func (oc *OperatorCreate) sqlSave(ctx context.Context) (*Operator, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Operator.ID type: %T", _spec.ID.Value)
		}
	}
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OperatorCreate) createSpec() (*Operator, *sqlgraph.CreateSpec) {
	var (
		_node = &Operator{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(operator.Table, sqlgraph.NewFieldSpec(operator.FieldID, field.TypeString))
	)
	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := oc.mutation.Name(); ok {
		_spec.SetField(operator.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := oc.mutation.LastLogin(); ok {
		_spec.SetField(operator.FieldLastLogin, field.TypeTime, value)
		_node.LastLogin = &value
	}
	if value, ok := oc.mutation.PublicKey(); ok {
		_spec.SetField(operator.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := oc.mutation.IsAdmin(); ok {
		_spec.SetField(operator.FieldIsAdmin, field.TypeBool, value)
		_node.IsAdmin = value
	}
	return _node, _spec
}

// OperatorCreateBulk is the builder for creating many Operator entities in bulk.
type OperatorCreateBulk struct {
	config
	err      error
	builders []*OperatorCreate
}

// Save creates the Operator entities in the database.
func (ocb *OperatorCreateBulk) Save(ctx context.Context) ([]*Operator, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Operator, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperatorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OperatorCreateBulk) SaveX(ctx context.Context) []*Operator {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OperatorCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OperatorCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
