// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nu11zy/rscc/internal/database/ent/session"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionCreate) SetCreatedAt(v time.Time) *SessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCreatedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *SessionCreate) SetAgentID(v string) *SessionCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *SessionCreate) SetUsername(v string) *SessionCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetHostname sets the "hostname" field.
func (_c *SessionCreate) SetHostname(v string) *SessionCreate {
	_c.mutation.SetHostname(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *SessionCreate) SetDomain(v string) *SessionCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *SessionCreate) SetNillableDomain(v *string) *SessionCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetIsPriv sets the "is_priv" field.
func (_c *SessionCreate) SetIsPriv(v bool) *SessionCreate {
	_c.mutation.SetIsPriv(v)
	return _c
}

// SetNillableIsPriv sets the "is_priv" field if the given value is not nil.
func (_c *SessionCreate) SetNillableIsPriv(v *bool) *SessionCreate {
	if v != nil {
		_c.SetIsPriv(*v)
	}
	return _c
}

// SetIps sets the "ips" field.
func (_c *SessionCreate) SetIps(v []string) *SessionCreate {
	_c.mutation.SetIps(v)
	return _c
}

// SetOsMeta sets the "os_meta" field.
func (_c *SessionCreate) SetOsMeta(v string) *SessionCreate {
	_c.mutation.SetOsMeta(v)
	return _c
}

// SetNillableOsMeta sets the "os_meta" field if the given value is not nil.
func (_c *SessionCreate) SetNillableOsMeta(v *string) *SessionCreate {
	if v != nil {
		_c.SetOsMeta(*v)
	}
	return _c
}

// SetProcName sets the "proc_name" field.
func (_c *SessionCreate) SetProcName(v string) *SessionCreate {
	_c.mutation.SetProcName(v)
	return _c
}

// SetNillableProcName sets the "proc_name" field if the given value is not nil.
func (_c *SessionCreate) SetNillableProcName(v *string) *SessionCreate {
	if v != nil {
		_c.SetProcName(*v)
	}
	return _c
}

// SetExtra sets the "extra" field.
func (_c *SessionCreate) SetExtra(v string) *SessionCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_c *SessionCreate) SetNillableExtra(v *string) *SessionCreate {
	if v != nil {
		_c.SetExtra(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v string) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableID(v *string) *SessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := session.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Domain(); !ok {
		v := session.DefaultDomain
		_c.mutation.SetDomain(v)
	}
	if _, ok := _c.mutation.IsPriv(); !ok {
		v := session.DefaultIsPriv
		_c.mutation.SetIsPriv(v)
	}
	if _, ok := _c.mutation.OsMeta(); !ok {
		v := session.DefaultOsMeta
		_c.mutation.SetOsMeta(v)
	}
	if _, ok := _c.mutation.ProcName(); !ok {
		v := session.DefaultProcName
		_c.mutation.SetProcName(v)
	}
	if _, ok := _c.mutation.Extra(); !ok {
		v := session.DefaultExtra
		_c.mutation.SetExtra(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := session.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Session.created_at"`)}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Session.agent_id"`)}
	}
	if v, ok := _c.mutation.AgentID(); ok {
		if err := session.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "Session.agent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Session.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := session.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Session.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hostname(); !ok {
		return &ValidationError{Name: "hostname", err: errors.New(`ent: missing required field "Session.hostname"`)}
	}
	if v, ok := _c.mutation.Hostname(); ok {
		if err := session.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Session.hostname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Session.domain"`)}
	}
	if _, ok := _c.mutation.IsPriv(); !ok {
		return &ValidationError{Name: "is_priv", err: errors.New(`ent: missing required field "Session.is_priv"`)}
	}
	if _, ok := _c.mutation.Ips(); !ok {
		return &ValidationError{Name: "ips", err: errors.New(`ent: missing required field "Session.ips"`)}
	}
	if _, ok := _c.mutation.OsMeta(); !ok {
		return &ValidationError{Name: "os_meta", err: errors.New(`ent: missing required field "Session.os_meta"`)}
	}
	if _, ok := _c.mutation.ProcName(); !ok {
		return &ValidationError{Name: "proc_name", err: errors.New(`ent: missing required field "Session.proc_name"`)}
	}
	if _, ok := _c.mutation.Extra(); !ok {
		return &ValidationError{Name: "extra", err: errors.New(`ent: missing required field "Session.extra"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(session.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Hostname(); ok {
		_spec.SetField(session.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(session.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.IsPriv(); ok {
		_spec.SetField(session.FieldIsPriv, field.TypeBool, value)
		_node.IsPriv = value
	}
	if value, ok := _c.mutation.Ips(); ok {
		_spec.SetField(session.FieldIps, field.TypeJSON, value)
		_node.Ips = value
	}
	if value, ok := _c.mutation.OsMeta(); ok {
		_spec.SetField(session.FieldOsMeta, field.TypeString, value)
		_node.OsMeta = value
	}
	if value, ok := _c.mutation.ProcName(); ok {
		_spec.SetField(session.FieldProcName, field.TypeString, value)
		_node.ProcName = value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(session.FieldExtra, field.TypeString, value)
		_node.Extra = value
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
