// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rscc/internal/database/ent/session"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *SessionCreate) SetCreatedAt(t time.Time) *SessionCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SessionCreate) SetNillableCreatedAt(t *time.Time) *SessionCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetAgentID sets the "agent_id" field.
func (sc *SessionCreate) SetAgentID(s string) *SessionCreate {
	sc.mutation.SetAgentID(s)
	return sc
}

// SetUsername sets the "username" field.
func (sc *SessionCreate) SetUsername(s string) *SessionCreate {
	sc.mutation.SetUsername(s)
	return sc
}

// SetHostname sets the "hostname" field.
func (sc *SessionCreate) SetHostname(s string) *SessionCreate {
	sc.mutation.SetHostname(s)
	return sc
}

// SetDomain sets the "domain" field.
func (sc *SessionCreate) SetDomain(s string) *SessionCreate {
	sc.mutation.SetDomain(s)
	return sc
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (sc *SessionCreate) SetNillableDomain(s *string) *SessionCreate {
	if s != nil {
		sc.SetDomain(*s)
	}
	return sc
}

// SetIsPriv sets the "is_priv" field.
func (sc *SessionCreate) SetIsPriv(b bool) *SessionCreate {
	sc.mutation.SetIsPriv(b)
	return sc
}

// SetNillableIsPriv sets the "is_priv" field if the given value is not nil.
func (sc *SessionCreate) SetNillableIsPriv(b *bool) *SessionCreate {
	if b != nil {
		sc.SetIsPriv(*b)
	}
	return sc
}

// SetIps sets the "ips" field.
func (sc *SessionCreate) SetIps(s []string) *SessionCreate {
	sc.mutation.SetIps(s)
	return sc
}

// SetOsMeta sets the "os_meta" field.
func (sc *SessionCreate) SetOsMeta(s string) *SessionCreate {
	sc.mutation.SetOsMeta(s)
	return sc
}

// SetNillableOsMeta sets the "os_meta" field if the given value is not nil.
func (sc *SessionCreate) SetNillableOsMeta(s *string) *SessionCreate {
	if s != nil {
		sc.SetOsMeta(*s)
	}
	return sc
}

// SetProcName sets the "proc_name" field.
func (sc *SessionCreate) SetProcName(s string) *SessionCreate {
	sc.mutation.SetProcName(s)
	return sc
}

// SetNillableProcName sets the "proc_name" field if the given value is not nil.
func (sc *SessionCreate) SetNillableProcName(s *string) *SessionCreate {
	if s != nil {
		sc.SetProcName(*s)
	}
	return sc
}

// SetExtra sets the "extra" field.
func (sc *SessionCreate) SetExtra(s string) *SessionCreate {
	sc.mutation.SetExtra(s)
	return sc
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (sc *SessionCreate) SetNillableExtra(s *string) *SessionCreate {
	if s != nil {
		sc.SetExtra(*s)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SessionCreate) SetID(s string) *SessionCreate {
	sc.mutation.SetID(s)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *SessionCreate) SetNillableID(s *string) *SessionCreate {
	if s != nil {
		sc.SetID(*s)
	}
	return sc
}

// Mutation returns the SessionMutation object of the builder.
func (sc *SessionCreate) Mutation() *SessionMutation {
	return sc.mutation
}

// Save creates the Session in the database.
func (sc *SessionCreate) Save(ctx context.Context) (*Session, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SessionCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SessionCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SessionCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := session.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.Domain(); !ok {
		v := session.DefaultDomain
		sc.mutation.SetDomain(v)
	}
	if _, ok := sc.mutation.IsPriv(); !ok {
		v := session.DefaultIsPriv
		sc.mutation.SetIsPriv(v)
	}
	if _, ok := sc.mutation.OsMeta(); !ok {
		v := session.DefaultOsMeta
		sc.mutation.SetOsMeta(v)
	}
	if _, ok := sc.mutation.ProcName(); !ok {
		v := session.DefaultProcName
		sc.mutation.SetProcName(v)
	}
	if _, ok := sc.mutation.Extra(); !ok {
		v := session.DefaultExtra
		sc.mutation.SetExtra(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := session.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SessionCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Session.created_at"`)}
	}
	if _, ok := sc.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Session.agent_id"`)}
	}
	if v, ok := sc.mutation.AgentID(); ok {
		if err := session.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "Session.agent_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Session.username"`)}
	}
	if v, ok := sc.mutation.Username(); ok {
		if err := session.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Session.username": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Hostname(); !ok {
		return &ValidationError{Name: "hostname", err: errors.New(`ent: missing required field "Session.hostname"`)}
	}
	if v, ok := sc.mutation.Hostname(); ok {
		if err := session.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Session.hostname": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Session.domain"`)}
	}
	if _, ok := sc.mutation.IsPriv(); !ok {
		return &ValidationError{Name: "is_priv", err: errors.New(`ent: missing required field "Session.is_priv"`)}
	}
	if _, ok := sc.mutation.Ips(); !ok {
		return &ValidationError{Name: "ips", err: errors.New(`ent: missing required field "Session.ips"`)}
	}
	if _, ok := sc.mutation.OsMeta(); !ok {
		return &ValidationError{Name: "os_meta", err: errors.New(`ent: missing required field "Session.os_meta"`)}
	}
	if _, ok := sc.mutation.ProcName(); !ok {
		return &ValidationError{Name: "proc_name", err: errors.New(`ent: missing required field "Session.proc_name"`)}
	}
	if _, ok := sc.mutation.Extra(); !ok {
		return &ValidationError{Name: "extra", err: errors.New(`ent: missing required field "Session.extra"`)}
	}
	return nil
}

func (sc *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.AgentID(); ok {
		_spec.SetField(session.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := sc.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := sc.mutation.Hostname(); ok {
		_spec.SetField(session.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	if value, ok := sc.mutation.Domain(); ok {
		_spec.SetField(session.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := sc.mutation.IsPriv(); ok {
		_spec.SetField(session.FieldIsPriv, field.TypeBool, value)
		_node.IsPriv = value
	}
	if value, ok := sc.mutation.Ips(); ok {
		_spec.SetField(session.FieldIps, field.TypeJSON, value)
		_node.Ips = value
	}
	if value, ok := sc.mutation.OsMeta(); ok {
		_spec.SetField(session.FieldOsMeta, field.TypeString, value)
		_node.OsMeta = value
	}
	if value, ok := sc.mutation.ProcName(); ok {
		_spec.SetField(session.FieldProcName, field.TypeString, value)
		_node.ProcName = value
	}
	if value, ok := sc.mutation.Extra(); ok {
		_spec.SetField(session.FieldExtra, field.TypeString, value)
		_node.Extra = value
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (scb *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Session, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
