// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentsColumns holds the columns for the "agents" table.
	AgentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "os", Type: field.TypeString},
		{Name: "arch", Type: field.TypeString},
		{Name: "server", Type: field.TypeString},
		{Name: "shared", Type: field.TypeBool, Default: false},
		{Name: "pie", Type: field.TypeBool, Default: false},
		{Name: "garble", Type: field.TypeBool, Default: false},
		{Name: "subsystems", Type: field.TypeJSON},
		{Name: "xxhash", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeBytes},
	}
	// AgentsTable holds the schema information for the "agents" table.
	AgentsTable = &schema.Table{
		Name:       "agents",
		Columns:    AgentsColumns,
		PrimaryKey: []*schema.Column{AgentsColumns[0]},
	}
	// ListenersColumns holds the columns for the "listeners" table.
	ListenersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "private_key", Type: field.TypeBytes},
	}
	// ListenersTable holds the schema information for the "listeners" table.
	ListenersTable = &schema.Table{
		Name:       "listeners",
		Columns:    ListenersColumns,
		PrimaryKey: []*schema.Column{ListenersColumns[0]},
	}
	// OperatorsColumns holds the columns for the "operators" table.
	OperatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "public_key", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
	}
	// OperatorsTable holds the schema information for the "operators" table.
	OperatorsTable = &schema.Table{
		Name:       "operators",
		Columns:    OperatorsColumns,
		PrimaryKey: []*schema.Column{OperatorsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentsTable,
		ListenersTable,
		OperatorsTable,
	}
)

func init() {
}
