// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ListenersColumns holds the columns for the "listeners" table.
	ListenersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "private_key", Type: field.TypeBytes},
	}
	// ListenersTable holds the schema information for the "listeners" table.
	ListenersTable = &schema.Table{
		Name:       "listeners",
		Columns:    ListenersColumns,
		PrimaryKey: []*schema.Column{ListenersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "last_activity", Type: field.TypeTime, Nullable: true},
		{Name: "public_key", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ListenersTable,
		UsersTable,
	}
)

func init() {
}
