// Code generated by ent, DO NOT EDIT.

package agent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agent type in the database.
	Label = "agent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldOs holds the string denoting the os field in the database.
	FieldOs = "os"
	// FieldArch holds the string denoting the arch field in the database.
	FieldArch = "arch"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// FieldShared holds the string denoting the shared field in the database.
	FieldShared = "shared"
	// FieldPie holds the string denoting the pie field in the database.
	FieldPie = "pie"
	// FieldGarble holds the string denoting the garble field in the database.
	FieldGarble = "garble"
	// FieldSubsystems holds the string denoting the subsystems field in the database.
	FieldSubsystems = "subsystems"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldXxhash holds the string denoting the xxhash field in the database.
	FieldXxhash = "xxhash"
	// Table holds the table name of the agent in the database.
	Table = "agents"
)

// Columns holds all SQL columns for agent fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldOs,
	FieldArch,
	FieldServer,
	FieldShared,
	FieldPie,
	FieldGarble,
	FieldSubsystems,
	FieldPublicKey,
	FieldXxhash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// OsValidator is a validator for the "os" field. It is called by the builders before save.
	OsValidator func(string) error
	// ArchValidator is a validator for the "arch" field. It is called by the builders before save.
	ArchValidator func(string) error
	// ServerValidator is a validator for the "server" field. It is called by the builders before save.
	ServerValidator func(string) error
	// DefaultShared holds the default value on creation for the "shared" field.
	DefaultShared bool
	// DefaultPie holds the default value on creation for the "pie" field.
	DefaultPie bool
	// DefaultGarble holds the default value on creation for the "garble" field.
	DefaultGarble bool
	// DefaultSubsystems holds the default value on creation for the "subsystems" field.
	DefaultSubsystems []string
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func([]byte) error
	// XxhashValidator is a validator for the "xxhash" field. It is called by the builders before save.
	XxhashValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Agent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByOs orders the results by the os field.
func ByOs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOs, opts...).ToFunc()
}

// ByArch orders the results by the arch field.
func ByArch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArch, opts...).ToFunc()
}

// ByServer orders the results by the server field.
func ByServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServer, opts...).ToFunc()
}

// ByShared orders the results by the shared field.
func ByShared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShared, opts...).ToFunc()
}

// ByPie orders the results by the pie field.
func ByPie(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPie, opts...).ToFunc()
}

// ByGarble orders the results by the garble field.
func ByGarble(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGarble, opts...).ToFunc()
}

// ByXxhash orders the results by the xxhash field.
func ByXxhash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXxhash, opts...).ToFunc()
}
