// Code generated by ent, DO NOT EDIT.

package agent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agent type in the database.
	Label = "agent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldOs holds the string denoting the os field in the database.
	FieldOs = "os"
	// FieldArch holds the string denoting the arch field in the database.
	FieldArch = "arch"
	// FieldServers holds the string denoting the servers field in the database.
	FieldServers = "servers"
	// FieldShared holds the string denoting the shared field in the database.
	FieldShared = "shared"
	// FieldPie holds the string denoting the pie field in the database.
	FieldPie = "pie"
	// FieldGarble holds the string denoting the garble field in the database.
	FieldGarble = "garble"
	// FieldSubsystems holds the string denoting the subsystems field in the database.
	FieldSubsystems = "subsystems"
	// FieldXxhash holds the string denoting the xxhash field in the database.
	FieldXxhash = "xxhash"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldHosted holds the string denoting the hosted field in the database.
	FieldHosted = "hosted"
	// FieldCallbacks holds the string denoting the callbacks field in the database.
	FieldCallbacks = "callbacks"
	// FieldDownloads holds the string denoting the downloads field in the database.
	FieldDownloads = "downloads"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// Table holds the table name of the agent in the database.
	Table = "agents"
)

// Columns holds all SQL columns for agent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldName,
	FieldComment,
	FieldOs,
	FieldArch,
	FieldServers,
	FieldShared,
	FieldPie,
	FieldGarble,
	FieldSubsystems,
	FieldXxhash,
	FieldPath,
	FieldURL,
	FieldHosted,
	FieldCallbacks,
	FieldDownloads,
	FieldPublicKey,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// OsValidator is a validator for the "os" field. It is called by the builders before save.
	OsValidator func(string) error
	// ArchValidator is a validator for the "arch" field. It is called by the builders before save.
	ArchValidator func(string) error
	// DefaultShared holds the default value on creation for the "shared" field.
	DefaultShared bool
	// DefaultPie holds the default value on creation for the "pie" field.
	DefaultPie bool
	// DefaultGarble holds the default value on creation for the "garble" field.
	DefaultGarble bool
	// DefaultSubsystems holds the default value on creation for the "subsystems" field.
	DefaultSubsystems []string
	// XxhashValidator is a validator for the "xxhash" field. It is called by the builders before save.
	XxhashValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// DefaultHosted holds the default value on creation for the "hosted" field.
	DefaultHosted bool
	// DefaultCallbacks holds the default value on creation for the "callbacks" field.
	DefaultCallbacks int
	// DefaultDownloads holds the default value on creation for the "downloads" field.
	DefaultDownloads int
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func([]byte) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Agent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByOs orders the results by the os field.
func ByOs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOs, opts...).ToFunc()
}

// ByArch orders the results by the arch field.
func ByArch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArch, opts...).ToFunc()
}

// ByShared orders the results by the shared field.
func ByShared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShared, opts...).ToFunc()
}

// ByPie orders the results by the pie field.
func ByPie(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPie, opts...).ToFunc()
}

// ByGarble orders the results by the garble field.
func ByGarble(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGarble, opts...).ToFunc()
}

// ByXxhash orders the results by the xxhash field.
func ByXxhash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXxhash, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByHosted orders the results by the hosted field.
func ByHosted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHosted, opts...).ToFunc()
}

// ByCallbacks orders the results by the callbacks field.
func ByCallbacks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallbacks, opts...).ToFunc()
}

// ByDownloads orders the results by the downloads field.
func ByDownloads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloads, opts...).ToFunc()
}
